using UnityEngine;
using System.Collections;

public class Unit : MonoBehaviour {
	
	public Transform target;
	public float speed = 20;

	Vector2[] path;
	int targetIndex;

	void Start() {
		//StartCoroutine (RefreshPath ());
	}

    void Update()
    {
        if(Input.GetMouseButtonDown(0))
        {
            Vector3 newPos = Camera.main.ScreenToWorldPoint(Input.mousePosition);
            newPos.z = 0;
            target.position = Pathfinding.instance.GetGrid().NodeFromWorldPoint(newPos).worldPosition;
            RequestPath();
        }
    }

    IEnumerator RefreshPath() {
		Vector2 targetPositionOld = (Vector2)target.position + Vector2.up; // ensure != to target.position initially
			
		while (true) {
			if (targetPositionOld != (Vector2)target.position) {
				targetPositionOld = (Vector2)target.position;

				path = Pathfinding.RequestPath (transform.position, target.position, transform.name);
				StopCoroutine ("FollowPath");
				StartCoroutine ("FollowPath");
			}

			yield return new WaitForSeconds (.25f);
		}
	}

    public void RequestPath()
    {
        path = Pathfinding.RequestPath(transform.position, target.position, transform.name);
        if(path != null)
        {
            StopCoroutine("FollowPath");
            StartCoroutine("FollowPath");
        }
    }

    IEnumerator FollowPath()
    {
		if (path != null && path.Length > 0)
        {
			targetIndex = 0;
			Vector2 currentWaypoint = path [0];

			while (true)
            {
				if ((Vector2)transform.position == currentWaypoint)
                {
					targetIndex++;
					if (targetIndex >= path.Length)
                    {
						yield break;
					}
					currentWaypoint = path [targetIndex];
				}

				transform.position = Vector2.MoveTowards (transform.position, currentWaypoint, speed * Time.deltaTime);
				yield return null;

			}
		}
	}

	public void OnDrawGizmos() {
		if (path != null) {
			for (int i = targetIndex; i < path.Length; i ++) {
				Gizmos.color = Color.black;
				//Gizmos.DrawCube((Vector3)path[i], Vector3.one *.5f);

				if (i == targetIndex) {
					Gizmos.DrawLine(transform.position, path[i]);
				}
				else {
					Gizmos.DrawLine(path[i-1],path[i]);
				}
			}
		}
	}
}
